### ISSUE TITLE
Zamysł bazy danych

### ISSUE THREAD

**Issue by SzymonJoszko** [Adam-Czerwinski/Przewidywanie-Pogody#1]
Stworzenie modelu bazy danych

**Comment by SzymonJoszko** [comment]
[SSIDtabaseSchema.pdf](https://github.com/Adam-Czerwinski/Przewidywanie-Pogody/files/3114171/SSIDtabaseSchema.pdf)

[SSIDatabaseDescription.txt](https://github.com/Adam-Czerwinski/Przewidywanie-Pogody/files/3114173/SSIDatabaseDescription.txt)
^ Zapisać z rozszerzeniem .html

Wstępna koncepcja. Od strony danych do uczenia myślę, że tak już zostanie więc można myśleć nad sql i programem wypełniającym bazę

**Comment by Adam-Czerwinski** [comment]
1. Dodać pole region do tabeli Miasta. **DODANO**
2. Zmienić Rodzaj danych na enum (Dane uczące, Dane testowe, Dane wprowadzane, Dane Rekurencyjne) **DODANO w pliku SSIDtabaseDescription**
3. Dodać pole boolowskie czyStacja do tabeli Miasta. Mówi czy dane miasto jest stacją (jednym z pięciu miast uczących). **DODANO Is_station**
4. Dodanie pole błąd sieci do tabeli ProcesNauki. **DODANO Total_error**
5. Dodanie pole boolowskie czyNauczona do tabeli ProcesNauki mówiące czy sieć się skończyła uczyć w danej generacji i czy są to ostateczne wyniki dla danej generacji. **DODANO**

Edit
Dodałem plik z pytaniami, które zadawaliśmy na zajęciach Połapowi
[PytaniaOProjekt.txt](https://github.com/Adam-Czerwinski/Przewidywanie-Pogody/files/3163948/PytaniaOProjekt.txt)

Ostatni edit 15.05.2019 15:32 
d92410c branch database

**Comment by SzymonJoszko** [comment]
Podstawa pod sieć gotowa!
