### ISSUE TITLE
Stworzenie klasy normalizującej dane 

### ISSUE THREAD

**Issue by SzymonJoszko** [Adam-Czerwinski/Przewidywanie-Pogody#3]
Należy stworzyć klasę normalizującą dane (`Temperature`, `Humidity`, `Speed`, `Cloudy`, `Visibility`) obiektu `Data` w przedziale [0;1] gdzie znormalizowana zmienna należy do zbioru liczb rzeczywistych. 

Pola obiektu `Data` :
`int Id`
`string Code`
`string Name`
`DateTime Date`
`int Hour`
`double Temperature` // do normalizacji z przedziału [-30;40] 
`int Humidity` // do normalizacji z przedziału [0;100] 
`string Direction`
`int Speed` // do normalizacji z przedziału [0;25] 
`int Cloudy` // do normalizacji z przedziału [0;8]
`int Visibility` // do normalizacji z przedziału [0;10]

Implementacje dodaj do brancha "Testing"

**Comment by Kendbi** [comment]
Czyli jednak nie przedział [-1; 1] dla tempertury?

**Comment by SzymonJoszko** [comment]
> Czyli jednak nie przedział [-1; 1] dla tempertury?
Wszystko musi być znormalizowane do jednego przedziału.
Wydaje mi się, że [0;1] jest lepszy.

**Comment by Adam-Czerwinski** [comment]
Polecam lepsze nazewnictwo. Np zamiast klasy "Data" to chociażby "Weather". Zamiast Speed -> WindSpeed. Dodatkowo utworzyć ENUM dla Direction (WindDirection) zamiast string. I też pokrótce skomentować składowe.

**Comment by Adam-Czerwinski** [comment]
Dodano klasę Normalization i Denormalization, a przy tym klasę w Business Object WeatherDataNormalized
